name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build
      run: xcodebuild clean build -scheme HeadsetControl-Status -configuration Release
