name: release
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: xcodebuild -scheme HeadsetControl-Status -configuration Release clean build

    - name: Create archive
      run: xcodebuild -scheme HeadsetControl-Status -configuration Release -archivePath build/archive archive

    - run: ls -R 

    - name: Export app
      run: xcodebuild -archivePath build/archive.xcarchive -exportArchive -exportPath ./release/HeadsetControl-Status.app -exportOptionsPlist ./exportOptions.plist
      env: 
        DEVELOPMENT_TEAM: "Personal"
