name: release
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2

    - name: Setup signing certificate
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

    - name: Create archive
      run: xcodebuild -scheme HeadsetControl-Status -configuration Release -archivePath build/archive archive

    # - name: Get release version
    #   run: xcodebuild -showBuildSettings | grep MARKETING_VERSION | sed 's/[ ]*MARKETING_VERSION = //'

    - name: Export app
      run: xcodebuild -archivePath build/archive.xcarchive -exportArchive -exportPath ./release/HeadsetControl-Status.app -exportOptionsPlist ./exportOptions.plist

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./release/HeadsetControl-Status.app
